name = 'isfreader'
version = '1.1.0'
description = 'Read Tek scope isf files as a numpy array.'
url = 'https://github.com/jeremitu/isfreader'
author = 'Justin Engel'
author_email = 'jengel@sealandaire.com'
